-- recurrent commands
SET LINESIZE 1000;
SET WRAP OFF;

SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER='FSDB308';

SELECT COUNT(*) FROM MUNICIPALITIES;

SELECT PASSPORT, phone_number, BIRTHDATE FROM BIBUSEROS;

SELECT COUNT(*), ROUTE_ID, STOPDATE FROM FSDB.BUSSTOPS  
    GROUP BY ROUTE_ID, STOPDATE; 

SELECT COUNT(*), ROUTE_ID, STOP_TIME FROM dL_Route_Stops WHERE ROWNUM < 10 GROUP BY ROUTE_ID, STOP_TIME;
SELECT COUNT(MUNICIPALITY_NAME, MUNICIPALITY_PROVINCE, ADDRESS), MUNICIPALITY_NAME, MUNICIPALITY_PROVINCE, ADDRESS FROM dL_Route_Stops where count(MUNICIPALITY_NAME, MUNICIPALITY_PROVINCE, ADDRESS) > 1


SELECT COUNT(*), MUNICIPALITY_PROVINCE FROM STOPS 
GROUP BY MUNICIPALITY_PROVINCE
HAVING COUNT(*) > 1;

SELECT USER_ID, SIGNATURE, DATE_TIME, RETURN, PASSPORT, TRIM(TOWN), TRIM(ADDRESS) 
FROM FSDB.LOANS
WHERE USER_ID='0016965023';

SELECT COUNT(*), RETURN 
FROM FSDB.LOANS
WHERE RETURN IS NOT NULL;


-- Siro
select name from municipalities where name LIKE '%Valverde%';
