SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER='FSDB308';

SELECT PASSPORT, phone_number, BIRTHDATE FROM BIBUSEROS;

SELECT COUNT(LAST_ITV), LAST_ITV FROM FSDB.BUSSTOPS GROUP BY LAST_ITV;
SELECT TO_TIMESTAMP('08.07.2024 // 23:22:22', 'dd.mm.yyyy // HH24:MI:SS') FROM FSDB.BUSSTOPS;
SELECT COUNT(LAST_ITV), TO_TIMESTAMP(LAST_ITV, 'dd.mm.yyyy // HH24.MI.SS') FROM FSDB.BUSSTOPS GROUP BY LAST_ITV;
SELECT COUNT(NEXT_ITV), NEXT_ITV FROM FSDB.BUSSTOPS GROUP BY NEXT_ITV;

SELECT COUNT(*), ROUTE_ID, STOPDATE FROM FSDB.BUSSTOPS  
    GROUP BY ROUTE_ID, STOPDATE; 

select name from municipalities where name LIKE '%Valverde%';
