INSERT INTO bibus VALUES();
INSERT INTO bibusero VALUES();
INSERT INTO municipality VALUES();
INSERT INTO books VALUES();

INSERT INTO route VALUES();
INSERT INTO stops VALUES();
INSERT INTO library VALUES();
INSERT INTO users VALUES();
INSERT INTO award VALUES();
INSERT INTO contribution VALUES();
INSERT INTO alternative_title VALUES();
INSERT INTO edition VALUES();

INSERT INTO sanctions VALUES();
INSERT INTO dL_route_stop VALUES();
INSERT INTO copy VALUES();
INSERT INTO add_language VALUES();

INSERT INTO user_loan VALUES();
INSERT INTO library_loan VALUES();

INSERT INTO comment VALUES();
