INSERT INTO Bibus (license_plate, last_itv, next_itv)
    SELECT DISTINCT MIN(PLATE), MAX(TO_DATE(LAST_ITV, 'dd.mm.yyyy // HH24.MI.SS')), MIN(TO_DATE(NEXT_ITV, 'dd.mm.yyyy'))
    FROM FSDB.BUSSTOPS
    WHERE plate IS NOT NULL AND last_itv IS NOT NULL AND next_itv IS NOT NULL
    GROUP BY PLATE;
;

INSERT INTO Bibusero VALUES();
-- LIB_PASSPORT CHAR(20)
-- LIB_EMAIL CHAR(100)
-- LIB_FULLNAME CHAR(80)
-- LIB_BIRTHDATE CHAR(10)
-- LIB_PHONE CHAR(9)
-- LIB_ADDRESS

INSERT INTO Municipality SELECT DISTINCT town, province, to_number(population) FROM fsdb.busstops;
INSERT INTO Books VALUES();

INSERT INTO Route VALUES();
INSERT INTO Stops VALUES();
INSERT INTO Library VALUES();
INSERT INTO Users VALUES();
INSERT INTO Awards VALUES();
INSERT INTO Contributors VALUES();
INSERT INTO AlternativeTitle VALUES();
INSERT INTO Edition VALUES();

INSERT INTO Sanctions VALUES();
INSERT INTO dL_Route_Stops VALUES();
INSERT INTO Copy VALUES();
INSERT INTO AdditionalLanguage VALUES();

INSERT INTO UserLoans VALUES();
INSERT INTO LibraryLoans VALUES();

INSERT INTO Comments VALUES();
